INFO 2025-04-22 03:19:17,745 autoreload Watching for file changes with StatReloader
INFO 2025-04-22 03:49:25,351 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 03:54:19,291 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 03:57:58,364 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 03:57:58,402 environment [ENV] 当前运行环境: development
INFO 2025-04-28 03:57:58,402 environment [ENV] 当前运行环境: development
INFO 2025-04-28 03:58:06,947 basehttp "GET / HTTP/1.1" 200 32335
INFO 2025-04-28 03:58:07,007 basehttp "GET /static/css/styles.css HTTP/1.1" 200 10923
INFO 2025-04-28 03:58:07,190 basehttp "GET /static/js/scripts.js HTTP/1.1" 200 10773
INFO 2025-04-28 03:58:10,099 basehttp "GET / HTTP/1.1" 200 32335
INFO 2025-04-28 03:58:13,627 basehttp "GET / HTTP/1.1" 200 32335
INFO 2025-04-28 03:58:14,598 basehttp "GET / HTTP/1.1" 200 32335
WARNING 2025-04-28 03:58:17,562 log Not Found: /favicon.ico
WARNING 2025-04-28 03:58:17,563 basehttp "GET /favicon.ico HTTP/1.1" 404 3816
INFO 2025-04-28 03:58:58,361 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 03:58:58,400 environment [ENV] 当前运行环境: development
INFO 2025-04-28 03:58:58,400 environment [ENV] 当前运行环境: development
INFO 2025-04-28 03:59:04,263 basehttp "GET / HTTP/1.1" 200 36117
INFO 2025-04-28 03:59:25,956 basehttp "GET / HTTP/1.1" 200 36117
INFO 2025-04-28 04:07:56,376 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 04:07:56,421 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:07:56,421 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:08:02,690 basehttp "GET / HTTP/1.1" 200 36214
INFO 2025-04-28 04:09:35,938 basehttp "GET / HTTP/1.1" 200 36232
INFO 2025-04-28 04:15:08,433 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 04:15:08,477 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:15:08,477 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:15:12,297 basehttp "GET / HTTP/1.1" 200 36382
INFO 2025-04-28 04:15:21,262 basehttp "GET / HTTP/1.1" 200 36382
INFO 2025-04-28 04:15:28,485 basehttp "GET / HTTP/1.1" 200 36382
INFO 2025-04-28 04:16:31,024 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 04:16:31,067 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:16:31,067 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:16:33,901 basehttp "GET / HTTP/1.1" 200 36550
INFO 2025-04-28 04:16:37,299 basehttp "GET / HTTP/1.1" 200 36550
INFO 2025-04-28 04:16:38,333 basehttp "GET / HTTP/1.1" 200 36550
INFO 2025-04-28 04:18:05,587 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 04:18:05,630 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:18:05,630 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:18:08,628 basehttp "GET / HTTP/1.1" 200 36551
INFO 2025-04-28 04:20:16,863 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 04:20:16,908 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:20:16,908 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:20:19,387 basehttp "GET / HTTP/1.1" 200 36970
INFO 2025-04-28 04:21:42,750 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 04:21:42,794 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:21:42,794 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:21:45,063 basehttp "GET / HTTP/1.1" 200 37737
INFO 2025-04-28 04:21:47,753 basehttp "GET / HTTP/1.1" 200 37737
INFO 2025-04-28 04:22:52,607 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 04:22:52,649 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:22:52,649 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:22:56,724 basehttp "GET / HTTP/1.1" 200 37648
INFO 2025-04-28 04:25:07,733 basehttp "GET / HTTP/1.1" 200 38098
INFO 2025-04-28 04:25:16,753 basehttp "GET / HTTP/1.1" 200 38098
INFO 2025-04-28 04:25:39,676 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 04:25:39,719 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:25:39,719 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:25:41,917 basehttp "GET / HTTP/1.1" 200 38098
INFO 2025-04-28 04:29:07,760 basehttp "GET / HTTP/1.1" 200 39232
INFO 2025-04-28 04:31:41,207 basehttp "GET / HTTP/1.1" 200 39369
INFO 2025-04-28 04:32:15,290 basehttp "GET / HTTP/1.1" 200 39380
INFO 2025-04-28 04:33:39,297 basehttp "GET / HTTP/1.1" 200 39401
INFO 2025-04-28 04:33:55,322 basehttp "GET / HTTP/1.1" 200 39401
INFO 2025-04-28 04:33:57,882 basehttp "GET / HTTP/1.1" 200 39401
INFO 2025-04-28 04:33:59,149 basehttp "GET / HTTP/1.1" 200 39401
INFO 2025-04-28 04:34:04,371 basehttp "GET / HTTP/1.1" 200 39410
INFO 2025-04-28 04:46:07,054 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 04:46:07,103 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:46:07,103 environment [ENV] 当前运行环境: development
INFO 2025-04-28 04:46:11,558 basehttp "GET / HTTP/1.1" 200 40030
INFO 2025-04-28 05:00:56,252 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 05:00:56,297 environment [ENV] 当前运行环境: development
INFO 2025-04-28 05:00:56,297 environment [ENV] 当前运行环境: development
INFO 2025-04-28 05:00:58,666 basehttp "GET / HTTP/1.1" 200 40833
INFO 2025-04-28 05:01:06,823 basehttp "GET / HTTP/1.1" 200 40844
INFO 2025-04-28 05:01:22,488 basehttp "GET / HTTP/1.1" 200 40840
INFO 2025-04-28 05:01:25,284 basehttp "GET / HTTP/1.1" 200 40840
INFO 2025-04-28 05:01:27,683 basehttp "GET / HTTP/1.1" 200 40840
INFO 2025-04-28 05:01:31,268 basehttp "GET / HTTP/1.1" 200 40840
INFO 2025-04-28 05:01:36,484 basehttp "GET / HTTP/1.1" 200 40840
INFO 2025-04-28 05:02:39,437 basehttp "GET / HTTP/1.1" 200 40840
INFO 2025-04-28 05:05:12,866 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 05:05:12,913 environment [ENV] 当前运行环境: development
INFO 2025-04-28 05:05:12,913 environment [ENV] 当前运行环境: development
INFO 2025-04-28 05:05:16,112 basehttp "GET / HTTP/1.1" 200 41416
INFO 2025-04-28 05:05:31,223 basehttp "GET / HTTP/1.1" 200 41416
INFO 2025-04-28 05:09:57,795 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 05:09:57,839 environment [ENV] 当前运行环境: development
INFO 2025-04-28 05:09:57,839 environment [ENV] 当前运行环境: development
INFO 2025-04-28 05:10:03,503 basehttp "GET / HTTP/1.1" 200 40841
INFO 2025-04-28 05:10:08,912 basehttp "GET / HTTP/1.1" 200 40841
INFO 2025-04-28 06:12:01,004 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 06:12:01,708 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-28 06:12:01,933 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-28 06:12:01,934 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-28 06:12:02,245 environment [ENV] 当前运行环境: development
INFO 2025-04-28 06:12:02,245 environment [ENV] 当前运行环境: development
INFO 2025-04-28 06:12:04,956 basehttp "GET / HTTP/1.1" 200 49656
INFO 2025-04-28 06:17:10,655 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 06:17:11,357 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-28 06:17:11,443 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-28 06:17:11,443 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-28 06:17:12,281 environment [ENV] 当前运行环境: development
INFO 2025-04-28 06:17:12,281 environment [ENV] 当前运行环境: development
INFO 2025-04-28 06:17:14,614 basehttp "GET / HTTP/1.1" 200 49673
INFO 2025-04-28 06:17:38,007 autoreload /home/runner/workspace/rush_car_rental/settings/development.py changed, reloading.
INFO 2025-04-28 06:20:50,900 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 06:20:50,961 environment [ENV] 当前运行环境: development
INFO 2025-04-28 06:20:50,961 environment [ENV] 当前运行环境: development
<<<<<<< HEAD
INFO 2025-04-28 10:29:28,457 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 10:29:28,500 environment [ENV] 当前运行环境: development
INFO 2025-04-28 10:29:28,500 environment [ENV] 当前运行环境: development
INFO 2025-04-28 10:29:32,621 basehttp "GET / HTTP/1.1" 200 39197
INFO 2025-04-28 10:33:47,919 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 10:33:47,962 environment [ENV] 当前运行环境: development
INFO 2025-04-28 10:33:47,962 environment [ENV] 当前运行环境: development
INFO 2025-04-28 10:33:57,594 basehttp "GET / HTTP/1.1" 200 41199
INFO 2025-04-29 07:46:59,800 autoreload Watching for file changes with StatReloader
INFO 2025-04-29 07:46:59,849 environment [ENV] 当前运行环境: development
INFO 2025-04-29 07:46:59,849 environment [ENV] 当前运行环境: development
INFO 2025-04-29 07:47:05,158 basehttp "GET / HTTP/1.1" 200 41184
INFO 2025-04-29 07:47:05,440 basehttp "GET /static/css/styles.css HTTP/1.1" 200 15816
=======
INFO 2025-04-28 10:21:06,168 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 10:21:07,644 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-28 10:21:07,936 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-28 10:21:07,936 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-28 10:21:08,598 environment [ENV] 当前运行环境: development
INFO 2025-04-28 10:21:08,598 environment [ENV] 当前运行环境: development
INFO 2025-04-28 10:21:10,741 basehttp "GET / HTTP/1.1" 200 49740
INFO 2025-04-29 08:29:55,907 autoreload Watching for file changes with StatReloader
INFO 2025-04-29 08:29:57,513 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-29 08:29:57,757 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-29 08:29:57,757 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-29 08:29:58,087 environment [ENV] 当前运行环境: development
INFO 2025-04-29 08:29:58,087 environment [ENV] 当前运行环境: development
INFO 2025-04-29 08:30:00,987 basehttp "GET / HTTP/1.1" 200 49704
INFO 2025-04-29 08:34:56,655 autoreload Watching for file changes with StatReloader
INFO 2025-04-29 08:34:57,330 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-29 08:34:57,432 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-29 08:34:57,433 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-29 08:35:00,192 environment [ENV] 当前运行环境: development
INFO 2025-04-29 08:35:00,192 environment [ENV] 当前运行环境: development
INFO 2025-04-29 08:35:02,538 basehttp "GET / HTTP/1.1" 200 49746
INFO 2025-04-29 08:35:18,348 basehttp "GET / HTTP/1.1" 200 49713
INFO 2025-04-29 08:35:18,399 basehttp "GET /static/css/styles.css HTTP/1.1" 200 15816
INFO 2025-04-29 08:35:18,464 basehttp "GET /static/js/scripts.js HTTP/1.1" 200 10773
INFO 2025-04-29 08:35:20,298 basehttp "GET / HTTP/1.1" 200 49689
>>>>>>> 154f309 (Generate technical documentation detailing the vehicle display and booking)
INFO 2025-04-30 05:56:03,194 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 05:56:04,628 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 05:56:04,841 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 05:56:04,841 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 05:56:07,789 environment [ENV] 当前运行环境: development
INFO 2025-04-30 05:56:07,789 environment [ENV] 当前运行环境: development
INFO 2025-04-30 09:38:53,602 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 09:38:55,101 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 09:38:55,341 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 09:38:55,341 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 09:38:55,630 environment [ENV] 当前运行环境: development
INFO 2025-04-30 09:38:55,630 environment [ENV] 当前运行环境: development
INFO 2025-04-30 09:39:07,234 basehttp "GET / HTTP/1.1" 200 50043
INFO 2025-04-30 09:39:42,448 basehttp "GET /static/css/styles.css HTTP/1.1" 200 15816
INFO 2025-04-30 10:44:33,007 autoreload /home/runner/workspace/cars/models.py changed, reloading.
INFO 2025-04-30 10:44:34,285 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 10:44:35,504 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 10:44:35,666 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 10:44:35,666 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 10:44:36,151 environment [ENV] 当前运行环境: development
INFO 2025-04-30 10:44:36,151 environment [ENV] 当前运行环境: development
ERROR 2025-04-30 10:44:39,813 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column cars_car.vehicle_category_id does not exist
LINE 1: ...el", "cars_car"."year", "cars_car"."category_id", "cars_car"...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/pages/views.py", line 20, in home
    return render(request, 'home.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column cars_car.vehicle_category_id does not exist
LINE 1: ...el", "cars_car"."year", "cars_car"."category_id", "cars_car"...
                                                             ^

ERROR 2025-04-30 10:44:39,819 basehttp "GET / HTTP/1.1" 500 263608
ERROR 2025-04-30 10:44:41,705 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column cars_car.vehicle_category_id does not exist
LINE 1: ...el", "cars_car"."year", "cars_car"."category_id", "cars_car"...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/pages/views.py", line 20, in home
    return render(request, 'home.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column cars_car.vehicle_category_id does not exist
LINE 1: ...el", "cars_car"."year", "cars_car"."category_id", "cars_car"...
                                                             ^

ERROR 2025-04-30 10:44:41,708 basehttp "GET / HTTP/1.1" 500 263610
ERROR 2025-04-30 10:44:42,894 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column cars_car.vehicle_category_id does not exist
LINE 1: ...el", "cars_car"."year", "cars_car"."category_id", "cars_car"...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/pages/views.py", line 20, in home
    return render(request, 'home.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column cars_car.vehicle_category_id does not exist
LINE 1: ...el", "cars_car"."year", "cars_car"."category_id", "cars_car"...
                                                             ^

ERROR 2025-04-30 10:44:42,897 basehttp "GET / HTTP/1.1" 500 263609
INFO 2025-04-30 10:45:18,586 autoreload /home/runner/workspace/cars/views.py changed, reloading.
INFO 2025-04-30 10:45:19,378 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 10:45:20,076 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 10:45:20,151 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 10:45:20,151 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 10:45:20,426 environment [ENV] 当前运行环境: development
INFO 2025-04-30 10:45:20,426 environment [ENV] 当前运行环境: development
ERROR 2025-04-30 10:45:23,284 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column cars_car.vehicle_category_id does not exist
LINE 1: ...el", "cars_car"."year", "cars_car"."category_id", "cars_car"...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/pages/views.py", line 20, in home
    return render(request, 'home.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column cars_car.vehicle_category_id does not exist
LINE 1: ...el", "cars_car"."year", "cars_car"."category_id", "cars_car"...
                                                             ^

ERROR 2025-04-30 10:45:23,288 basehttp "GET / HTTP/1.1" 500 263612
ERROR 2025-04-30 10:45:24,473 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column cars_car.vehicle_category_id does not exist
LINE 1: ...el", "cars_car"."year", "cars_car"."category_id", "cars_car"...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/pages/views.py", line 20, in home
    return render(request, 'home.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column cars_car.vehicle_category_id does not exist
LINE 1: ...el", "cars_car"."year", "cars_car"."category_id", "cars_car"...
                                                             ^

ERROR 2025-04-30 10:45:24,475 basehttp "GET / HTTP/1.1" 500 263612
ERROR 2025-04-30 10:45:25,683 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column cars_car.vehicle_category_id does not exist
LINE 1: ...el", "cars_car"."year", "cars_car"."category_id", "cars_car"...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/pages/views.py", line 20, in home
    return render(request, 'home.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column cars_car.vehicle_category_id does not exist
LINE 1: ...el", "cars_car"."year", "cars_car"."category_id", "cars_car"...
                                                             ^

ERROR 2025-04-30 10:45:25,685 basehttp "GET / HTTP/1.1" 500 263615
INFO 2025-04-30 10:48:13,201 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 10:48:13,913 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 10:48:14,064 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 10:48:14,064 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 10:48:14,347 environment [ENV] 当前运行环境: development
INFO 2025-04-30 10:48:14,347 environment [ENV] 当前运行环境: development
ERROR 2025-04-30 10:48:16,156 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column cars_car.vehicle_category_id does not exist
LINE 1: ...el", "cars_car"."year", "cars_car"."category_id", "cars_car"...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/pages/views.py", line 20, in home
    return render(request, 'home.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column cars_car.vehicle_category_id does not exist
LINE 1: ...el", "cars_car"."year", "cars_car"."category_id", "cars_car"...
                                                             ^

ERROR 2025-04-30 10:48:16,160 basehttp "GET / HTTP/1.1" 500 262541
INFO 2025-04-30 10:48:46,794 autoreload /home/runner/workspace/cars/urls.py changed, reloading.
INFO 2025-04-30 10:48:47,502 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 10:48:48,204 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 10:48:48,276 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 10:48:48,277 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 10:48:48,545 environment [ENV] 当前运行环境: development
INFO 2025-04-30 10:48:48,545 environment [ENV] 当前运行环境: development
INFO 2025-04-30 10:49:06,769 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 10:49:06,885 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 10:49:06,886 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 10:49:27,295 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 10:49:27,391 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 10:49:27,392 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 10:52:10,865 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 10:52:11,567 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 10:52:11,659 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 10:52:11,659 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 10:52:11,925 environment [ENV] 当前运行环境: development
INFO 2025-04-30 10:52:11,925 environment [ENV] 当前运行环境: development
INFO 2025-04-30 10:52:13,034 basehttp "GET / HTTP/1.1" 200 50048
INFO 2025-04-30 10:52:13,070 basehttp "GET /static/css/styles.css HTTP/1.1" 200 15816
INFO 2025-04-30 10:52:13,079 basehttp "GET /static/js/scripts.js HTTP/1.1" 200 10773
INFO 2025-04-30 10:53:30,649 basehttp "GET / HTTP/1.1" 200 50090
INFO 2025-04-30 16:27:54,794 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 16:27:55,801 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 16:27:56,113 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 16:28:45,672 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 16:28:45,759 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 16:28:45,760 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 16:29:55,199 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 16:29:56,095 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 16:29:56,235 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 16:29:56,235 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 16:30:00,141 environment [ENV] 当前运行环境: development
INFO 2025-04-30 16:30:00,141 environment [ENV] 当前运行环境: development
INFO 2025-04-30 16:30:01,428 basehttp "GET / HTTP/1.1" 200 34615
INFO 2025-04-30 16:30:01,458 basehttp "GET /static/css/styles.css HTTP/1.1" 200 15816
INFO 2025-04-30 16:30:01,567 basehttp "GET /static/js/scripts.js HTTP/1.1" 200 10773
INFO 2025-04-30 16:31:08,386 basehttp "GET / HTTP/1.1" 200 41026
INFO 2025-04-30 16:31:08,647 basehttp "GET /static/images/car-placeholder.jpg HTTP/1.1" 200 56241
INFO 2025-04-30 16:31:12,420 basehttp "GET / HTTP/1.1" 200 41054
INFO 2025-04-30 16:31:13,017 basehttp "GET / HTTP/1.1" 200 41032
INFO 2025-04-30 16:31:14,040 basehttp "GET /static/css/styles.css HTTP/1.1" 304 0
INFO 2025-04-30 16:31:14,104 basehttp "GET /static/images/car-placeholder.jpg HTTP/1.1" 200 56241
INFO 2025-04-30 16:31:15,175 basehttp "GET /static/js/scripts.js HTTP/1.1" 304 0
ERROR 2025-04-30 16:36:47,328 log Internal Server Error: /cars/
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/cars/views.py", line 74, in car_list
    return render(request, 'cars/car_list.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_booking' with no arguments not found. 1 pattern(s) tried: ['bookings/create/(?P<car_id>[0-9]+)/\\Z']
ERROR 2025-04-30 16:36:47,334 basehttp "GET /cars/?pickup_location=Sydney%2C+NSW&pickup_date=Fri+04+Apr&pickup_time=11%3A00+AM&return_date=Sat+05+Apr&return_time=11%3A00+AM&pickup_time=11%3A00+AM&return_time=11%3A00+AM HTTP/1.1" 500 332244
INFO 2025-04-30 16:38:26,517 autoreload /home/runner/workspace/bookings/views.py changed, reloading.
INFO 2025-04-30 16:38:27,533 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 16:38:28,472 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 16:38:28,565 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 16:38:28,567 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 16:38:30,485 environment [ENV] 当前运行环境: development
INFO 2025-04-30 16:38:30,485 environment [ENV] 当前运行环境: development
INFO 2025-04-30 16:38:46,056 autoreload /home/runner/workspace/bookings/views.py changed, reloading.
INFO 2025-04-30 16:38:46,733 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 16:38:47,389 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 16:38:47,463 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 16:38:47,464 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 16:38:47,768 environment [ENV] 当前运行环境: development
INFO 2025-04-30 16:38:47,768 environment [ENV] 当前运行环境: development
INFO 2025-04-30 16:39:14,918 autoreload /home/runner/workspace/bookings/views.py changed, reloading.
INFO 2025-04-30 16:39:15,657 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 16:39:16,334 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 16:39:16,406 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 16:39:16,407 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 16:39:16,681 environment [ENV] 当前运行环境: development
INFO 2025-04-30 16:39:16,681 environment [ENV] 当前运行环境: development
INFO 2025-04-30 16:39:32,767 autoreload /home/runner/workspace/bookings/views.py changed, reloading.
INFO 2025-04-30 16:39:33,683 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 16:39:34,452 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 16:39:34,540 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 16:39:34,540 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 16:39:34,853 environment [ENV] 当前运行环境: development
INFO 2025-04-30 16:39:34,853 environment [ENV] 当前运行环境: development
INFO 2025-04-30 16:39:47,908 autoreload /home/runner/workspace/bookings/views.py changed, reloading.
INFO 2025-04-30 16:39:48,674 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 16:39:49,620 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 16:39:49,721 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 16:39:49,722 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 16:39:49,989 environment [ENV] 当前运行环境: development
INFO 2025-04-30 16:39:49,989 environment [ENV] 当前运行环境: development
INFO 2025-04-30 16:40:12,200 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 16:40:12,845 _util message='Request to Stripe api' method=get url=https://api.stripe.com/v1/account
INFO 2025-04-30 16:40:12,918 _util message='Stripe API response' path=https://api.stripe.com/v1/account response_code=401
INFO 2025-04-30 16:40:12,918 _util error_code=None error_message='Invalid API Key provided: sk_test' error_param=None error_type=invalid_request_error message='Stripe v1 API error received'
INFO 2025-04-30 16:40:13,198 environment [ENV] 当前运行环境: development
INFO 2025-04-30 16:40:13,198 environment [ENV] 当前运行环境: development
INFO 2025-04-30 16:40:14,011 basehttp "GET / HTTP/1.1" 200 41045
